stages:
  mermaid-md:
    desc: Create directed acylic graph of the pipeline as mermaid file.
    always_changed: true
    cmd: >
      dvc dag pipeline/dvc.yaml --full --mermaid --md
      | sed 's/pipeline\/dvc.yaml://'
      >> dag.md
    outs:
    - dag.md:
        cache: false

  mermaid-readme:
    desc: Put the mermaid diagram into the README
    cmd: cat dag.md | sed 's/^/3i/' | sed -f- README.template > README.md
    deps:
    - dag.md
    - README.template
    outs:
    - README.md:
        cache: false

  requirements:
    desc:
      For reproducibility, freeze the state of pip after every run. If one wants to
      reproduce a particular run, one can use `pip install -r frozen.txt` inside a
      blank new virtual environment to get exactly the setup that was used to obtain
      these results.
    always_changed: true
    cmd: pip freeze | grep -v "pkg_resources" > frozen.txt
    outs:
    - frozen.txt:
        cache: false
